### ISSUE TITLE
几个建议

### ISSUE THREAD

**Issue by gaoluhua99** [zcqian/tjupt#14]
建议对平台进行一下说明。大致有哪些要求。
对https和http建议有所规范。如搭建好了以后采用http登陆 但是发布页Tracker服务器的URL是: https://
试着上传，也提示一些错误：
上传失败！
mysql puked: Incorrect integer value: '' for column 'subsinfo' at row 1

**Comment by tongyifan** [comment]
谢谢建议！
平台的话的确没有写，我会加在README中。目前生产环境是用的是
- Debian 4.9.110-3+deb9u6
- PHP 5.6（分支dev_php7中有PHP7的版本，前几天把代码洗了一遍能正常运行了但是不知道有没有其他bug）
- MariaDB 10.1.26（新版的应该也能用，我的开发环境用的是最新的版本）
- Memcached
- nginx（用来反代php-fpm）

https和http的确有很多都是硬写在代码中的，但其实它们应该使用get_protocol_prefix()方法来获取。而且其实本项目还有很多硬写在代码中的部分，包括announce.php中一堆关于tracker地址的判断，还有download.php中硬写在torrent中的tracker地址（而不是使用原本NexusPHP自带的配置tracker的方法）等等，的确不太适合直接使用，需要修改很多地方。（功能实现的比较急没有考虑复用）

最后那个上传失败的我暂时没有什么思路，似乎是传到takeupload.php的subsinfo的值是空值，但是事实上如果不填字幕情况的话会弹窗报错missing data，并不会上传上去。。我暂时没法复现，如果可以的话麻烦详细描述一下。

**Comment by Rhilip** [comment]
@tongyifan 
get_protocol_prefix() 在 类似
```
header("Location: " . get_protocol_prefix() . "$BASEURL/xxxxxxx");
header("Refresh: 0; url=" . get_protocol_prefix() . "$BASEURL/xxxxxx");
````
的使用都可以洗成使用相对地址的方法，让User-Agent来做处理
```
header("Location:  /xxxxxxx");
header("Refresh: 0; url=/xxxxxx");
````

**Comment by tongyifan** [comment]
@Rhilip 
:+1:的确是这样，抽时间我再过一遍

**Comment by gaoluhua99** [comment]
相对的地址的问题。本身在配置文件中就有关于网站地址的设置，是否可以调用该地址。假如网站设置成xxxxxxxx.xx/abc/  也就加一层或几层路径，这时尽管也能打开网站，但是有些文件的路径就错了，如.css的路径，也就是相对地址的不统一。

**Comment by tongyifan** [comment]
@gaoluhua99 对于你信中问题的回复
[tjupt-dev_php7使用-1.docx](https://github.com/zcqian/tjupt/files/2618562/tjupt-dev_php7.-1.docx)

问题一：
事实上是这样的，NO_ZERO_IN_DATE和NO_ZERO_DATE是新版MySQL新加入的特性，这在以前的版本中是不会报错的。而本项目提供的数据库中很多时间的默认值都是0000-00-00 00:00:00，所以在新版的数据库中需要设置这些设置。

问题二：
我觉得问题应该出在发信失败上，或许你需要将注册后的发信验证关闭（站点设定->主要设置->用户验证方式->自动）或者配置好SMTP服务。

问题三：


问题四：
那个库是为外部SMTP服务器准备的，你需要修改站点设置中的SMTP设置，修改里面的地址，端口等等。我在最新的commit中尝试修复了一下那个库，但愿它还好用。

问题五：
本项目的捐赠系统是用的是有赞的sdk，通过有赞的接口生成收款码来收款，需要使用composer安装hanson/youzan-sdk来使用，并且需要修改allconfig.php  最后关于有赞的部分（具体如何申请请自行查阅有赞开发者平台的文档），包括clientid, clientsecret, kdtid，后面的为奖励策略，格式是「魔力值，上传量（GB），邀请码，捐赠者标志，VIP」，其中前三个可以使用倍数，例如魔力值设置为“1000x”意味着捐赠奖励为1000x金额（元）个魔力值。

**Comment by tongyifan** [comment]
> 相对的地址的问题。本身在配置文件中就有关于网站地址的设置，是否可以调用该地址。假如网站设置成xxxxxxxx.xx/abc/ 也就加一层或几层路径，这时尽管也能打开网站，但是有些文件的路径就错了，如.css的路径，也就是相对地址的不统一。

是这样的，我在部署我本地的环境的时候就遇到了这个问题，但是有点懒得改hhhh

**Comment by tongyifan** [comment]
> 相对的地址的问题。本身在配置文件中就有关于网站地址的设置，是否可以调用该地址。假如网站设置成xxxxxxxx.xx/abc/ 也就加一层或几层路径，这时尽管也能打开网站，但是有些文件的路径就错了，如.css的路径，也就是相对地址的不统一。

是这样的，我在部署我本地的环境的时候就遇到了这个问题，但是有点懒得改hhhh

**Comment by gaoluhua99** [comment]
SMTP的配置项在SMTP设置和主要设置里面是配置好的，在nexusphp上可以正常进行使用。我弄的那个试验站点上也是配置好的。
http://tjupt.i6u6.com/mailtest.php
*Parse error*: syntax error, unexpected 'new' (T_NEW) in
*/usr/local/nginx/html/tjupt-dev_php7/include/smtp/smtp.lib.php* on line
*307*


问题5准备尝试下做做。谢谢。

Yifan Tong <notifications@github.com> 于2018年11月27日周二 下午2:14写道：

**Comment by tongyifan** [comment]
或许你可以拉取git最新版本尝试一下
