### ISSUE TITLE
你好 该程序我校可以使用嘛？

### ISSUE THREAD

**Issue by greatvpn** [zcqian/tjupt#15]
你好 该程序我校可以使用嘛？

**Comment by tongyifan** [comment]
可以使用，但是需要改的地方有很多（很多是针对TJUPT现有环境写的，没有考虑复用或者实现方式使其无法复用），需要一个能有耐心改完所有地方的程序员。。

如果想用的话建议使用dev_php7分支，并且可以参考一下issue #14 ，有对于这个分支的一些解释和踩的一些坑
