### ISSUE TITLE
使用PHP7.1宝塔面板安装出现错误

### ISSUE THREAD

**Issue by haig233** [zcqian/tjupt#18]
```
SQL query list:
SET NAMES UTF8
SET collation_connection = 'utf8_general_ci'
SELECT * FROM bans WHERE 2028957749 >= first AND 2028957749 <= last
SELECT * FROM users WHERE users.id = 1 AND users.enabled='yes' AND users.status = 'confirmed' LIMIT 1
UPDATE users SET last_access = '2019-04-09 14:09:09',ip = '120.239.112.53' WHERE id = 1
Memcached key read:
current_ad_array : 1
stylesheet_content : 1
user_1_css : 2
category_icon_content : 1
upload_rates : 1
user_1_inbox_count : 1
user_1_outbox_count : 1
user_1_connect : 1
user_1_active_seed_count : 1
user_1_active_leech_count : 1
user_1_unread_message_count : 1
nontjuip : 1
staff_report_count : 1
staff_message_count : 1
staff_cheater_count : 1
user_1_unread_news_count : 1
staff_new_report_count : 1
staff_new_message_count : 1
staff_new_cheater_count : 1
Memcached key write:
user_1_content : 1
```

[root@stspt ~]# php -v
PHP 7.1.5 (cli) (built: Jun  5 2017 18:00:45) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
[root@stspt ~]# nginx -v
nginx version: nginx/1.15.9
[root@stspt ~]# mysql -V
mysql  Ver 14.14 Distrib 5.5.57, for Linux (x86_64) using readline 5.1
[root@stspt ~]#

**Comment by tongyifan** [comment]
具体错误是什么呢？我没有在你给出的日志输出中发现问题

**Comment by haig233** [comment]
![Snipaste_2019-04-09_16-06-57.png](https://i.loli.net/2019/04/09/5cac52b43255e.png)
![Snipaste_2019-04-09_16-06-42.png](https://i.loli.net/2019/04/09/5cac52b43acfb.png)
出现在网站底部的代码

**Comment by tongyifan** [comment]
这是给SysOP及以上等级调试用的，你创建一个SysOP以下的普通账户就看不到这些代码了

**Comment by haig233** [comment]
好的知道了，对了，怎么修改页面？比如顶部图片，还有配色啊等等

**Comment by tongyifan** [comment]
具体功能上及代码上的问题请自行摸索后再来提问

另，本项目的tracker等部分功能针对TJUPT的特殊网络情况进行了改动，无编程经验的话不建议使用此套源码，请知悉

**Comment by Rhilip** [comment]
(付费获取额外支持23333

**Comment by tongyifan** [comment]
23333333正解
