### ISSUE TITLE
[security] commits history has sensitive information

### ISSUE THREAD

**Issue by lomanyong** [zcqian/tjupt#2]
Hi, your commits history is not clean enough. There is sensitive information in your commit history, including the database connection configuration. You can try to clear the old commits history, with git commands like `git reset --hard #hash` and `git push -f origin branch`, to remove the commits which may have the sensitive information.

**Comment by zcqian** [comment]
Thanks for the reminder.

We are not using those credentials anymore, but it is still a very helpful reminder.
